% figure 1C
% ---------

% read data generated by G-power
data        = importdata('GPower_data.csv'); % assuming already in current directory
effectsized = data.data(:,1);                % Cohens' d values
N80         = data.data(:,2);                % Sample sizes for 80% power
N95         = data.data(:,3);                % Sample sizes for 95% power
CI          = [0.77 1.26];                   % meta-analysis Hedges' g 95% CI
CI          = CI./(1-(3/((4*17)-1)));        % approximate transformation to Cohens' d 
                                             % with 17 df (from 18 studies) 

% plot
figure; plot(N80./2,effectsized,'-o','LineWidth',3)
hold on; plot(N95./2,effectsized,'-o','LineWidth',3)
box on; grid on; ylabel('Cohen''s d'); xlabel('Sample Size per group')
axis([0 95 0.45 1.65 ]); title('Two-sample t-test power curves')
plot(0:95,repmat(CI(1),96,1),'-k','LineWidth',2)   % lower bound of the 95% CI
plot(0:95,repmat(CI(2),96,1),'-k','LineWidth',2)  % higher bound of the 95% CI
